# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampledocument',
            options={'permissions': (('modify_sampledocument', 'Modify SampleDocument'), ('review_sampledocument', 'Review SampleDocument'), ('cancel_sampledocument', 'Cancel SampleDocument'))},
        ),
    ]
