# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='service_type',
            field=models.CharField(choices=[(b'service', b'Service'), (b'deliverable', b'Deliverable'), (b'non-deliverable', b'Non-Deliverable')], default='service', max_length=20),
            preserve_default=False,
        ),
    ]
