# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('flowkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.SlugField(blank=True, help_text='Internal (unique) code', max_length=20, verbose_name='Code'),
        ),
    ]
